# 1. You push code to Github
# 2. CircleCI runs your tests
# 3. If your tests pass, then CircleCI will build the app
# 4. CircleCI with then copy the build product to the droplet.

version: 2

general:
  # list of branches to build
  branches:
    only:
      - master
      - dev

jobs:
  build:
    docker:
      # specify the version you desire here
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/node:9.2.0

    working_directory: ~/repo

    steps:
      # Check versions
      - run:
          name: Checking Versions
          command: |
            node --version
            npm --version

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps
      - run:
          name: Install NPM dependencies
          # command: npm ci  #### npm version 5.8+
          command: npm i
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      # Build and Test
      - run:
          name: Build application
          command: npm run build

      # - run:
      #     name: Tests
      #     command: npm test

      - run:
          name: Echo env
          command: env

      # Deploy and profit
      - run:
          name: Update Code in Droplet
          # note: the '.' after the source file is needed -- it tells scp to copy contents of the directory
          command: scp -oStrictHostKeyChecking=no -r ./build/. ${DROPLET_USER}@${DROPLET_IP}:${DROPLET_PATH}/build

